DIRECTORIO_CLASES=lib/classes
CLASES_PROYECTO=build/classes
ARCHIVO_JAR=JXMLTool.jar
all:
	rm $(ARCHIVO_JAR); jar -cvfe $(ARCHIVO_JAR) io.github.oscarmaestre.jxmltool.Interfaz -C $(DIRECTORIO_CLASES) . \
							-C $(CLASES_PROYECTO) . 
